bad_chars = '.:",;()\'<>^&#'
DATA_FOLDER_PATH = './data/'
PREPROCESSED_TRAINING_FILE_PATH = DATA_FOLDER_PATH + "preprocessed_data"
WORD2VEC_MODEL_FILE_PATH = DATA_FOLDER_PATH + "word2vec_model"
DATASET_PATH = DATA_FOLDER_PATH + "dataset"
POSITIVE_WORDS_PATH = DATA_FOLDER_PATH + "positives"
NEGATIVE_WORDS_PATH = DATA_FOLDER_PATH + "negatives"
ML_MODEL_PATH = DATA_FOLDER_PATH + "predictor_model"
WIKI_FILE_PATH = DATA_FOLDER_PATH + "trwiki-20180101-pages-articles.xml.bz2"

TRAIN_FOLDER_PATH = "./Train/"
TRAIN_POSITIVE_PATH = TRAIN_FOLDER_PATH + "positive_train"
TRAIN_NEGATIVE_PATH = TRAIN_FOLDER_PATH + "negative_train"
TRAIN_NOTR_PATH = TRAIN_FOLDER_PATH + "notr_train"

TEST_SET_PATH = TRAIN_FOLDER_PATH+"negative-train"